name: 'Sam Sparks '
favicon: null
layout_spectrum: 0.09595077810809016
typography_spectrum: 0.5740434071049094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.18306088796816766
  lightness: 0.23392745340242982
  saturation: 0.4207149618305266
  rhythmicContrast: 0.988841327605769
purpose: []
